# -*- coding: utf-8 -*-
"""final_embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H5qVuT6oLqPOrC_7oWhtN86nWv1edFwV
"""

import pandas as pd
import os
import torch
from transformers import MarianTokenizer, MarianMTModel

MODEL_NAME = "Helsinki-NLP/opus-mt-mul-en"   # multilingual - English

def tamil_to_english_marian(source_path, text_column_name, output_file):

    if not os.path.exists(source_path):
        print(f"File not found: {source_path}")
        return

    df = pd.read_csv(source_path)
    sentences = df[text_column_name].astype(str).tolist()

    print("Loading MarianMT multilingual -> English model...")
    tokenizer = MarianTokenizer.from_pretrained(MODEL_NAME)
    model = MarianMTModel.from_pretrained(MODEL_NAME)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    model.to(device)

    translations = []
    for text in sentences:

        # Tokenize
        encoded = tokenizer.prepare_seq2seq_batch([text], return_tensors="pt").to(device)

        # Generate translation
        generated = model.generate(
            **encoded,
            max_new_tokens=128
        )

        english = tokenizer.decode(generated[0], skip_special_tokens=True)
        translations.append(english)

    df["Marian_English"] = translations
    df.to_csv(output_file, index=False)

    print(f"Saved to {output_file}")
    return df


# Run translation
df = tamil_to_english_marian(
    source_path="tamil_thirukkural_test.csv",
    text_column_name="kural",
    output_file="translated_tamil_thirukkural.csv"
)

